spring:
    mvc:
        converters:
            preferred-json-mapper: gson
    gson:
        pretty-printing: true
        serialize-nulls: false
    task:
        scheduling:
            pool:
                size: 10
            shutdown:
                await-termination: true
            thread-name-prefix: scheduledTaskExecutor
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
        show-sql: true
    datasource:
        url: 'jdbc:postgresql://ec2-52-30-161-203.eu-west-1.compute.amazonaws.com:5432/d31necqj0jdkfd'
        username: 'citilsprqeawyr'
        password: '85a60dfa388dc909f5f5bbb5df0bde6cde19bf625cce893f258f213ac30da967'
auth:
    token:
        secret-key: 'K%hM3+3eX6-^tL*BhDYya@V!53aSBH!q'
