server:
  error:
    include-message: always
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    show-sql: true
  datasource:
    url: 'jdbc:postgresql://database-1.cet8g3oroazx.us-east-2.rds.amazonaws.com:5432/postgres'
    username: 'postgres'
    password: '15ab0c7de1f9gh98'
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "noreply.spaceapps@gmail.com"
    password: "vfkimfzzassvqiku"
    protocol: "smtp"
    starttls: true
    auth: true
springfox:
  documentation:
    swagger:
      use-model-v3: false
firebase:
  service-account-file: 'spaceapps-firebase-adminsdk.json'
  database-url: 'https://spaceapps-5465e.firebaseio.com'
logging:
  level:
    root: INFO
    com.spaceapps.backend: TRACE