server:
  error:
    include-message: always
  port: 5000
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    show-sql: true
  datasource:
    url: 'jdbc:postgresql://aaxld5u1ejav8s.cet8g3oroazx.us-east-2.rds.amazonaws.com:5432/aaxld5u1ejav8s '
    username: 'citilsprqeawyr'
    password: '85a60dfa388dc909f5f5bbb5df0bde6cde19bf625cce893f258f213ac30da967'
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "noreply.spaceapps@gmail.com"
    password: "vfkimfzzassvqiku"
    protocol: "smtp"
    starttls: true
    auth: true
springfox:
  documentation:
    swagger:
      use-model-v3: false
firebase:
  service-account-file: 'spaceapps-firebase-adminsdk.json'
  database-url: 'https://spaceapps-5465e.firebaseio.com'
logging:
  level:
    root: INFO
    com.spaceapps.backend: TRACE