package com.spaceapps.backend

const val AUTH_TOKEN_HEADER = "Authorization"
const val AUTH_TOKEN_PREFIX = "Bearer "

const val UNAUTHORIZED = "UNAUTHORIZED"
const val USER_DOES_NOT_EXISTS = "USER DOES NOT EXISTS"
const val USER_ALREADY_EXISTS = "USER ALREADY EXISTS"
const val WRONG_PASSWORD = "WRONG PASSWORD"
const val EMAIL_NOT_VALID = "EMAIL NOT VALID"
const val PASSWORD_NOT_VALID = "PASSWORD NOT VALID"
const val INCORRECT_MESSAGE_ID = "INCORRECT MESSAGE ID"
const val INCORRECT_FEED_ID = "INCORRECT FEED ID"
const val INCORRECT_COMMENT_ID = "INCORRECT COMMENT ID"
const val INCORRECT_FILE_NAME = "INCORRECT FILE NAME"
const val INVALID_RESET_CODE = "INVALID RESET CODE"